'use client';

import { cn, formatBytes } from '@/lib/utils';
import {
    ArrowLeft,
    ChevronRight,
    Download,
    File,
    Folder,
    FolderOpen,
    Plus,
    Trash2
} from 'lucide-react';
import { useState } from 'react';

interface FileItem {
    name: string;
    type: 'file' | 'directory';
    size?: number;
    modified: string;
}

const mockFiles: Record<string, FileItem[]> = {
    '/': [
        { name: 'resources', type: 'directory', modified: '2 hr ago' },
        { name: 'cache', type: 'directory', modified: '5 min ago' },
        { name: 'data', type: 'directory', modified: '1 day ago' },
        { name: 'server.cfg', type: 'file', size: 4250, modified: '3 hr ago' },
        { name: 'server-data.json', type: 'file', size: 1280, modified: '1 hr ago' },
        { name: 'run.sh', type: 'file', size: 256, modified: '7 days ago' },
    ],
    '/resources': [
        { name: '[core]', type: 'directory', modified: '1 day ago' },
        { name: '[gameplay]', type: 'directory', modified: '2 hr ago' },
        { name: '[ui]', type: 'directory', modified: '3 hr ago' },
        { name: 'es_extended', type: 'directory', modified: '1 hr ago' },
        { name: 'ox_inventory', type: 'directory', modified: '2 hr ago' },
        { name: 'ox_lib', type: 'directory', modified: '3 days ago' },
    ],
};

const mockFileContent = `# FXServer Configuration
# Generated by Saif Control

endpoint_add_tcp "0.0.0.0:30120"
endpoint_add_udp "0.0.0.0:30120"

sv_hostname "My FiveM Server"
sv_maxclients 128
sv_licenseKey "changeme"

set onesync on
set onesync_distanceCullVehicles on
set onesync_forceMigration on

# Resources
ensure mapmanager
ensure chat
ensure spawnmanager
ensure sessionmanager
ensure basic-gamemode
ensure hardcap
ensure es_extended
ensure ox_lib
ensure ox_inventory
`;

export default function FilesPage() {
    const [currentPath, setCurrentPath] = useState('/');
    const [selectedFile, setSelectedFile] = useState<string | null>(null);
    const [fileContent, setFileContent] = useState<string | null>(null);

    const files = mockFiles[currentPath] ?? [];

    const navigateTo = (name: string) => {
        const newPath = currentPath === '/' ? `/${name}` : `${currentPath}/${name}`;
        setCurrentPath(newPath);
        setSelectedFile(null);
        setFileContent(null);
    };

    const goUp = () => {
        const parts = currentPath.split('/').filter(Boolean);
        parts.pop();
        setCurrentPath('/' + parts.join('/'));
        setSelectedFile(null);
        setFileContent(null);
    };

    const openFile = (name: string) => {
        setSelectedFile(name);
        setFileContent(mockFileContent);
    };

    const breadcrumbs = ['root', ...currentPath.split('/').filter(Boolean)];

    return (
        <div className="p-6 space-y-6 max-w-[1600px] mx-auto">
            <div className="flex items-center justify-between">
                <div>
                    <h1 className="text-2xl font-semibold text-foreground">Files</h1>
                    <p className="text-sm text-muted-foreground mt-1">Browse and edit server files</p>
                </div>
                <div className="flex items-center gap-2">
                    <button className="flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium bg-accent/30 text-muted-foreground hover:text-foreground transition-colors">
                        <Plus className="w-3.5 h-3.5" />
                        New File
                    </button>
                    <button className="flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium bg-accent/30 text-muted-foreground hover:text-foreground transition-colors">
                        <Folder className="w-3.5 h-3.5" />
                        New Folder
                    </button>
                </div>
            </div>

            {/* Breadcrumb */}
            <div className="flex items-center gap-1 text-xs text-muted-foreground">
                {breadcrumbs.map((crumb, i) => (
                    <div key={i} className="flex items-center gap-1">
                        {i > 0 && <ChevronRight className="w-3 h-3" />}
                        <button
                            onClick={() => {
                                if (i === 0) setCurrentPath('/');
                                else setCurrentPath('/' + breadcrumbs.slice(1, i + 1).join('/'));
                                setSelectedFile(null);
                                setFileContent(null);
                            }}
                            className="hover:text-foreground transition-colors"
                        >
                            {crumb}
                        </button>
                    </div>
                ))}
            </div>

            <div className="grid grid-cols-1 xl:grid-cols-[1fr_1fr] gap-6">
                {/* File browser */}
                <div className="glass-panel">
                    {currentPath !== '/' && (
                        <button
                            onClick={goUp}
                            className="flex items-center gap-2 w-full px-5 py-2.5 text-xs text-muted-foreground hover:text-foreground hover:bg-accent/30 transition-colors border-b border-border"
                        >
                            <ArrowLeft className="w-3 h-3" />
                            Back
                        </button>
                    )}
                    {files.map((file) => (
                        <button
                            key={file.name}
                            onClick={() => file.type === 'directory' ? navigateTo(file.name) : openFile(file.name)}
                            className={cn(
                                'flex items-center gap-3 w-full px-5 py-2.5 text-left hover:bg-accent/30 transition-colors',
                                selectedFile === file.name && 'bg-accent/40',
                            )}
                        >
                            {file.type === 'directory' ? (
                                <FolderOpen className="w-4 h-4 text-yellow-400 shrink-0" />
                            ) : (
                                <File className="w-4 h-4 text-blue-400 shrink-0" />
                            )}
                            <span className="flex-1 text-sm text-foreground">{file.name}</span>
                            {file.size != null && (
                                <span className="text-[10px] text-muted-foreground">{formatBytes(file.size)}</span>
                            )}
                            <span className="text-[10px] text-muted-foreground">{file.modified}</span>
                            {file.type === 'directory' && <ChevronRight className="w-3 h-3 text-muted-foreground" />}
                        </button>
                    ))}
                    {files.length === 0 && (
                        <div className="px-5 py-12 text-center text-sm text-muted-foreground">Directory is empty</div>
                    )}
                </div>

                {/* File editor */}
                <div className="glass-panel flex flex-col">
                    {selectedFile ? (
                        <>
                            <div className="flex items-center justify-between px-5 py-3 border-b border-border">
                                <div className="flex items-center gap-2">
                                    <File className="w-4 h-4 text-blue-400" />
                                    <span className="text-sm font-medium text-foreground">{selectedFile}</span>
                                </div>
                                <div className="flex items-center gap-1">
                                    <button className="p-1.5 rounded hover:bg-accent/50 text-muted-foreground hover:text-foreground transition-colors">
                                        <Download className="w-3.5 h-3.5" />
                                    </button>
                                    <button className="p-1.5 rounded hover:bg-red-500/20 text-muted-foreground hover:text-red-400 transition-colors">
                                        <Trash2 className="w-3.5 h-3.5" />
                                    </button>
                                </div>
                            </div>
                            <textarea
                                value={fileContent ?? ''}
                                onChange={(e) => setFileContent(e.target.value)}
                                className="flex-1 p-4 bg-transparent font-mono text-xs text-foreground resize-none outline-none min-h-[400px] custom-scrollbar"
                                spellCheck={false}
                            />
                            <div className="flex items-center justify-between px-5 py-2 border-t border-border">
                                <span className="text-[10px] text-muted-foreground">
                                    {fileContent?.split('\n').length ?? 0} lines
                                </span>
                                <button className="px-3 py-1.5 rounded-md text-xs font-medium bg-primary text-primary-foreground hover:bg-primary/90 transition-colors">
                                    Save Changes
                                </button>
                            </div>
                        </>
                    ) : (
                        <div className="flex-1 flex items-center justify-center p-12">
                            <div className="text-center space-y-2">
                                <File className="w-8 h-8 mx-auto text-muted-foreground opacity-40" />
                                <p className="text-sm text-muted-foreground">Select a file to view or edit</p>
                            </div>
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}
